# Generated by Django 5.0.2 on 2024-02-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetails',
            new_name='StudentDetail',
        ),
    ]
