# Generated by Django 5.0.2 on 2024-02-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_rename_studentdetails_studentdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='admissiondate',
            new_name='admissionDate',
        ),
        migrations.RenameField(
            model_name='studentdetail',
            old_name='gname',
            new_name='guardianName',
        ),
        migrations.RenameField(
            model_name='studentdetail',
            old_name='sid',
            new_name='studentId',
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='std',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
