# Generated by Django 5.0.2 on 2024-02-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_alter_studentdetail_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentdetail',
            table='StudentDetail',
        ),
    ]
