# Generated by Django 5.0.2 on 2024-02-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_studentdetail_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guardianName', models.CharField(max_length=100)),
                ('std', models.PositiveSmallIntegerField()),
                ('studentId', models.CharField(max_length=100)),
                ('admissionDate', models.DateField()),
            ],
            options={
                'db_table': 'AddStudentDetail',
            },
        ),
    ]
