# Generated by Django 5.0.2 on 2024-02-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_addstudentdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddStudentDetail',
        ),
    ]
