# Generated by Django 5.0.2 on 2024-02-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_feestracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestracker',
            old_name='n',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feestracker',
            old_name='stdr',
            new_name='std',
        ),
        migrations.RenameField(
            model_name='feestracker',
            old_name='stId',
            new_name='studentId',
        ),
    ]
