# Generated by Django 5.0.2 on 2024-02-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_rename_n_feestracker_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feestracker',
            table=None,
        ),
        migrations.AlterModelTable(
            name='studentdetail',
            table=None,
        ),
    ]
