# Generated by Django 5.0.2 on 2024-02-13 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_alter_feestracker_table_alter_studentdetail_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('std', models.PositiveSmallIntegerField()),
                ('studentId', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='feestracker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='feestracker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feestracker',
            name='std',
        ),
        migrations.RemoveField(
            model_name='feestracker',
            name='studentId',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='std',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='studentId',
        ),
        migrations.AddField(
            model_name='feestracker',
            name='basic_ptr',
            field=models.OneToOneField(auto_created=True, default=1000, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.basic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='basic_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.basic'),
            preserve_default=False,
        ),
    ]
