# Generated by Django 5.0.2 on 2024-02-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0012_basic_remove_feestracker_id_remove_feestracker_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='basic_ptr',
        ),
        migrations.RemoveField(
            model_name='feestracker',
            name='basic_ptr',
        ),
        migrations.AddField(
            model_name='feestracker',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1111111, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestracker',
            name='n',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestracker',
            name='sId',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestracker',
            name='stdr',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='std',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='studentId',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='feestracker',
            table='FeesTracker',
        ),
        migrations.AlterModelTable(
            name='studentdetail',
            table='StudentDetail',
        ),
        migrations.DeleteModel(
            name='basic',
        ),
    ]
