# Generated by Django 5.0.2 on 2024-02-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_remove_studentdetail_basic_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeesTracker',
        ),
    ]
