# Generated by Django 5.0.2 on 2024-02-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0014_delete_feestracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='admissionDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='guardianName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='std',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='studentId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
