# Generated by Django 5.0.2 on 2024-02-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0015_alter_studentdetail_admissiondate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesTracker',
            fields=[
                ('studentdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.studentdetail')),
                ('jan', models.BooleanField()),
                ('feb', models.BooleanField()),
                ('mar', models.BooleanField()),
                ('april', models.BooleanField()),
                ('may', models.BooleanField()),
                ('june', models.BooleanField()),
                ('july', models.BooleanField()),
                ('aug', models.BooleanField()),
                ('sept', models.BooleanField()),
                ('oct', models.BooleanField()),
                ('nov', models.BooleanField()),
                ('dec', models.BooleanField()),
            ],
            options={
                'db_table': 'FeesTracker',
            },
            bases=('fees.studentdetail',),
        ),
    ]
