# Generated by Django 5.0.2 on 2024-02-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0016_feestracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeesTracker',
        ),
    ]
