# Generated by Django 5.0.2 on 2024-02-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0017_delete_feestracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='april',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='aug',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='dec',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='feb',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='jan',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='july',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='june',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='mar',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='may',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='nov',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='oct',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='sept',
            field=models.BooleanField(null=True),
        ),
    ]
