# Generated by Django 5.0.2 on 2024-02-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0020_alter_studentdetail_admissiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='admissionDate',
            field=models.DateField(null=True),
        ),
    ]
