# Generated by Django 5.0.2 on 2024-02-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0023_alter_studentdetail_admissiondate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='admissionDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='april',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='aug',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='dec',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='feb',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='guardianName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='jan',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='july',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='june',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='mar',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='may',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='nov',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='oct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='sept',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='std',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='studentId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
