# Generated by Django 5.0.2 on 2024-02-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0024_alter_studentdetail_admissiondate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='april',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='aug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='dec',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='feb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='jan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='july',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='june',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='mar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='may',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='nov',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='oct',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='sept',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
